-- 테이블(table)
-- 데이터가 저장되는 객체
-- 표 형태이다

CREATE TABLE ATTENDANCE(
NO NUMBER(10),
NAME VARCHAR2(21),
PHONE CHAR(13)
);

DROP TABLE ATTENDANCE;

-- Day08 월드컵 테이블 예제
 CREATE TABLE WORLDCUP(
 RANK NUMBER(3),
 NAME VARCHAR(39),
 NATION VARCHAR(15),
 GOAL NUMBER(2)
 );
SELECT * FROM WORLDCUP;
DELETE WORLDCUP;
 ROLLBACK ;
 
 --Day08 포켓몬 테이블 예제
 CREATE TABLE POCKETMON(
 NO NUMBER(3),          -- 숫자를 안쓰면 자동으로 38자리가 됨
 NAME VARCHAR2(21),
 TYPE VARCHAR2(9)
 );
 DROP TABLE POCKETMON;
 
 --Day08 메달리스트 테이블 예제
 CREATE TABLE MEDALIST(
 NAME VARCHAR2(21),
 EVENT VARCHAR2(12),
 TYPE CHAR(6),             -- 고정된 글자에 char
 GOLD NUMBER(2),
 SILVER NUMBER(2),
 BRONZE NUMBER(2)
 );
 DROP TABLE MEDALIST;
 
