-- 대표항목은 겹치지 않는것으로 (식별값)
-- DAY08에 있는 요금제 테이블에 조건을 부여해서 생성

 CREATE TABLE PLAN(
 TELECOM CHAR(2) NOT NULL CHECK(TELECOM IN('SK','KT','LG')),    -- NOT NULL(비어있을 수 없음) (중복가능하면 생략) CHECK(조건체크)
 NAME VARCHAR2(60) NOT NULL UNIQUE,                               -- UNIQUE (중복 불가)
 PRICE NUMBER NOT NULL CHECK(PRICE>=0),
 DATA NUMBER NOT NULL CHECK(DATA>=0),
 CALL NUMBER NOT NULL CHECK(CALL>=0),
SMS NUMBER NOT NULL CHECK(SMS>=0)
);

-- 이상데이터 추가 테스트
INSERT INTO PLAN(TELECOM,NAME,PRICE,DATA,CALL,SMS)
VALUES(NULL,NULL,NULL,NULL,NULL,NULL);                      -- 첫번째 NOT NULL 에서부터 막힘

INSERT INTO PLAN(TELECOM,NAME,PRICE,DATA,CALL,SMS)
VALUES('GS','5G 언택트 52',52000,200,1000,2000);               -- 조건에서 막힘

INSERT INTO PLAN(TELECOM,NAME,PRICE,DATA,CALL,SMS)
VALUES('SK','5G 언택트 52',-52000,200,1000,2000);              -- 숫자 음수 조건에서 막힘

-- 정상데이터 (UNIQUE 때문에 두번 추가는 안된다)
INSERT INTO PLAN(TELECOM,NAME,PRICE,DATA,CALL,SMS)
VALUES('SK','5G 언택트 52',52000,200,1000,2000);

-- DAY08 메뉴테이블 

CREATE TABLE MENU(
NAME VARCHAR2(24) NOT NULL UNIQUE,
TYPE VARCHAR2(9) NOT NULL CHECK(TYPE IN('음료','디저트')),
PRICE NUMBER NOT NULL CHECK(PRICE >= 0),
EVENT CHAR(9) CHECK(EVENT = '행사중')
);
DROP TABLE MENU;

INSERT INTO MENU(NAME,TYPE,PRICE,EVENT)
VALUES('아메리카노','음료',2500,'행사중');
INSERT INTO MENU(NAME,TYPE,PRICE)               -- NULL 이라면 생략가능
VALUES('모카라떼','음료',3500);
INSERT INTO MENU(NAME,TYPE,PRICE,EVENT)
VALUES('치즈케이크','디저트',5000,'행사중');
INSERT INTO MENU(NAME,TYPE,PRICE,EVENT)
VALUES('마카롱','디저트',3000,NULL);
COMMIT;

SELECT*FROM MENU;


/* 
    자바에서의 논리는 데이터베이스에서 0과1로 처리한다
    0은 FALSE, 1은 TRUE로 사용
*/

CREATE TABLE MENU(
NAME VARCHAR2(24) NOT NULL UNIQUE,
TYPE VARCHAR2(9) NOT NULL CHECK(TYPE IN('음료','디저트')),
PRICE NUMBER NOT NULL CHECK(PRICE >= 0),
EVENT CHAR(1) NOT NULL CHECK(EVENT IN('0','1')) 
);

INSERT INTO MENU(NAME,TYPE,PRICE,EVENT)
VALUES('아메리카노','음료',2500,'1');
INSERT INTO MENU(NAME,TYPE,PRICE,EVENT)               
VALUES('모카라떼','음료',3500,'0');
INSERT INTO MENU(NAME,TYPE,PRICE,EVENT)
VALUES('치즈케이크','디저트',5000,'1');
INSERT INTO MENU(NAME,TYPE,PRICE,EVENT)
VALUES('마카롱','디저트',3000,'0');
COMMIT;

SELECT*FROM MENU;

