-- DAY08 휴대폰 판매정보 테이블

CREATE TABLE MOBILE(
NAME VARCHAR2(16) NOT NULL,
TELECOM CHAR(2)NOT NULL CHECK(TELECOM IN('KT','SK','LG')),
PRICE NUMBER NOT NULL CHECK(PRICE>0),
MONTH NUMBER(2) CHECK(MONTH IN(24,30,36)),
UNIQUE(NAME,TELECOM)                                        -- 둘중 하나라도 다르면 가능 , 둘다 같으면 불가능
);
DROP TABLE MOBILE;


INSERT INTO MOBILE(NAME,TELECOM,PRICE,MONTH)
VALUES('갤럭시22S','SK',1800000,NULL);
INSERT INTO MOBILE(NAME,TELECOM,PRICE,MONTH)
VALUES('갤럭시22S','KT',1750000,24);
INSERT INTO MOBILE(NAME,TELECOM,PRICE,MONTH)
VALUES('아이폰14','LG',2000000,30);
INSERT INTO MOBILE(NAME,TELECOM,PRICE,MONTH)
VALUES('아이폰14','SK',1990000,NULL);
COMMIT;
SELECT*FROM MOBILE;