-- DAY09 학원 강의 요금표 문제
CREATE SEQUENCE SUBJECT_SEQ;

CREATE TABLE SUBJECT(
NO NUMBER PRIMARY KEY,
NAME VARCHAR2(40) NOT NULL,
PERIOD NUMBER NOT NULL CHECK(MOD(PERIOD,30)=0),
PRICE NUMBER NOT NULL CHECK(PRICE>0),
TYPE VARCHAR2(12) NOT NULL CHECK(TYPE IN('온라인','오프라인','혼합'))
);

DROP TABLE SUBJECT;

INSERT INTO SUBJECT(NO,NAME,PERIOD,PRICE,TYPE)
VALUES(SUBJECT_SEQ.NEXTVAL,'자바마스터과정',90,1000000,'온라인');
INSERT INTO SUBJECT(NO,NAME,PERIOD,PRICE,TYPE)
VALUES(SUBJECT_SEQ.NEXTVAL,'파이썬기초',60,600000,'온라인');
INSERT INTO SUBJECT(NO,NAME,PERIOD,PRICE,TYPE)
VALUES(SUBJECT_SEQ.NEXTVAL,'웹개발자단기완성',120,1200000,'오프라인');
COMMIT;
SELECT*FROM SUBJECT;